M48
; DRILL file {KiCad 8.0.0-rc1} date 2024-04-25T14:23:12+0300
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-25T14:23:12+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0-rc1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0394
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0551
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T5C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T6C0.1280
%
G90
G05
T1
X7.3929Y-3.765
X7.7071Y-3.765
T2
X7.6736Y-6.0813
T3
X6.8299Y-3.1823
X6.8299Y-4.489
T4
X7.6736Y-5.2939
T5
X2.6126Y-6.5118
X3.0626Y-6.5118
T6
X3.8224Y-1.087
X4.9445Y-1.087
X5.2722Y-1.0858
X7.6384Y-1.0858
M30
